

#ifndef ENUM_LOGLEVEL_H_
#define ENUM_LOGLEVEL_H_

enum LogLevelEnum
{
    MY_LOG_LEVEL_SILENT = 0,
    MY_LOG_LEVEL_FATAL = 1,
    MY_LOG_LEVEL_ERROR = 2,
    MY_LOG_LEVEL_WARNING = 3,
    MY_LOG_LEVEL_INFO = 4,
    MY_LOG_LEVEL_NOTICE = 4,
    MY_LOG_LEVEL_TRACE = 5,
    MY_LOG_LEVEL_VERBOSE = 6
};

#endif